# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b7c8cc3f-55bd-4ab2-9d65-446031fcf747";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/638ab06f-e919-4799-b129-45efe66a4641"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
